<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->addColumn('player', 'action_points', 'integer', '8', array(
             'default' => '0',
             ));
    }

    public function down()
    {
		$this->removeColumn('player', 'action_points');
    }
}