<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
  public function up() {
		$this->addColumn('player', 'attack_general', 'integer', '8', array(
      'default' => '0',
    ));
		$this->addColumn('player', 'attack_weapon_main', 'integer', '8', array(
      'default' => '0',
    ));
		$this->addColumn('player', 'attack_weapon_off', 'integer', '8', array(
      'default' => '0',
    ));
		$this->addColumn('player', 'attack_implement', 'integer', '8', array(
      'default' => '0',
    ));
		$this->changeColumn('power', 'attack_bonus', '8', 'integer', array(
    'default' => '0',
    ));
  }

  public function down() {
		$this->removeColumn('player', 'attack_general');
		$this->removeColumn('player', 'attack_weapon_main');
		$this->removeColumn('player', 'attack_weapon_off');
		$this->removeColumn('player', 'attack_implement');
  }
}