<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
  public function up() {
	  $this->removeColumn('player', 'health_max');
	  $this->removeColumn('player', 'surges_max');
	  $this->removeColumn('player', 'surge_value');
	  
	  $this->addColumn('player', 'health_bonus', 'integer', '8', array(
      'default' => '0',
    ));
	  $this->addColumn('player', 'surges_bonus', 'integer', '8', array(
      'default' => '0',
    ));
	  $this->addColumn('player', 'surge_value_bonus', 'integer', '8', array(
      'default' => '0',
    ));
  }

  public function down() {
	  $this->addColumn('player', 'health_max', 'integer', '8', array());
	  $this->addColumn('player', 'surges_max', 'integer', '8', array());
	  $this->addColumn('player', 'surge_value', 'integer', '8', array());
	  
	  $this->removeColumn('player', 'health_bonus');
	  $this->removeColumn('player', 'surges_bonus');
	  $this->removeColumn('player', 'surge_value_bonus');
  }
}