<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
  public function up() {
		$this->addColumn('player', 'magic_item_uses', 'integer', '8', array(
      'default' => '0',
    ));
		$this->addColumn('power', 'item', 'boolean', '25', array());
		$this->changeColumn('power', 'use_type', '', 'enum', array(
      'values' => array(
        0 => '1_atwill',
        1 => '2_encounter',
        2 => '3_daily',
        3 => '4_surge',
      ),
      'default' => '1_atwill',
    ));
  }

  public function down() {
		$this->removeColumn('player', 'magic_item_uses');
		$this->removeColumn('power', 'item');
  }
}
?>