options:
  collate: utf8_unicode_ci
  charset: utf8

Race:
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
      unsigned: 1
    name: string(50)

Archetype:
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
      unsigned: 1
    name: string(50)
    health_first: integer
    health_level: integer
    surges: integer
    
Player:
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
      unsigned: 1
    name: string(50)
    level: integer
    attack_general:
        type: integer
        default: 0
    attack_weapon_main:
        type: integer
        default: 0
    attack_weapon_off:
        type: integer
        default: 0
    attack_implement:
        type: integer
        default: 0
    action_points:
        type: integer
        default: 0
    health_cur: integer
    health_bonus:
        type: integer
        default: 0
    health_tmp:
      type: integer
      default: 0
    surges_cur: integer
    surges_bonus:
      type: integer
      default: 0
    surge_value_bonus:
      type: integer
      default: 0
    strength: integer
    dexterity: integer
    constitution: integer
    intelligence: integer
    wisdom: integer
    charisma: integer
    race_id:
      type: integer(8)
      unsigned: 1
    archetype_id:
      type: integer(8)
      unsigned: 1
    notes: clob
  relations:
    Race:
      foreignAlias: Characters
    Archetype:
      foreignAlias: Characters

Power:
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
      unsigned: 1
    name: string(255)
    level: integer
    use_type: 
      type: enum
      # This is to fix sorting by use_type
      values: ['1_atwill','2_encounter','3_daily']
      default: 1_atwill
    action:
      type: enum
      values: ['standard','move','minor','free','reaction','interrupt','none']
      default: standard
    power_range: string(255)
    target: string(255)
    attack_ability:
      type: enum
      values: ['Str','Dex','Con','Int','Wis','Cha','none']
      default: none
    attack_bonus: 
      type: integer
      default: 0
    defense:
      type: enum
      values: ['AC','Fort','Ref','Will']
      default: AC
    hit: clob
    miss: clob
    effect: clob
    sustain_action:
      type: enum
      values: ['Standard','Move','Minor','Free','none']
      default: none
    sustain: clob
    notes: clob
    used: boolean
    player_id:
      type: integer
      unsigned: 1
  relations:
    Player:
      foreignAlias: Powers
    Keywords:
      foreignAlias: Powers
      class: Keyword
      refClass: PowerKeyword

Keyword:
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
      unsigned: 1
    name: string(255)

PowerKeyword:
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
      unsigned: 1
    power_id:
      type: integer(8)
      unsigned: 1
    keyword_id:
      type: integer(8)
      unsigned: 1
  relations:
    Power:
      foreignAlias: PowerKeywords
    Keyword:
      foreignAlias: PowerKeywords
